# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --mode=production --if-present
    
  deploy:
      # if: ${{ always() }}
      needs: [build]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        # cache 
        - name: Cache node modules
          id: cache-node-modules
          uses: actions/cache@v3
          env:
              cache-name: cache-node-modules
          with:
            # npm cache files are stored in `~/.npm` on Linux/macOS
            path: node_modules
            key: ${{ runner.os }}-${{ matrix.node-version }}-nodeModules-${{ hashFiles('yarn.lock') }}-${{ hashFiles('package.json') }}
            restore-keys: | 
              ${{ runner.os }}-${{ matrix.node-version }}-nodeModules-

        - name: Install Modules
          if: steps.cache-node-modules.outputs.cache-hit != 'true'
          run: yarn 

        - run: npm run build --mode=production
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist
      
